#ifndef OTA_TYPES_H
#define OTA_TYPES_H

typedef enum
{
    OTA_STATUS_IDLE = 0,
    OTA_STATUS_PENDING,
    OTA_STATUS_DOWNLOADING,
    OTA_STATUS_VERIFIED,
    OTA_STATUS_INSTALLING,
    OTA_STATUS_VALIDATING,
    OTA_STATUS_SUCCESS,
    OTA_STATUS_FAILED,
    OTA_STATUS_ROLLED_BACK

} ota_status_t;

#endif
